#! /bin/bash

source ./parse_mem

# parse_vnic_stats is used to parse _nic_stats_vnic

dev=${1:-0}  # The device number of nfp
vnic=${2:-0} # The vNIC ID

# There are 64 counters for each vnic, each counter is 64-bits counter
nfp-rtsym -n$dev -l512 -v -o ./.vnic_stats_data.txt _nic_stats_vnic:$((vnic*512))

echo nfp$dev.vnic$vnic statistics:
parse_mem_for_64_bits_counters ./.vnic_stats_data.txt ./vnic_stats
