#! /bin/bash

source ./parse_mem

# parse_vnic_stats is used to parse _nic_stats_vnic

dev=${1:-0}  # The device number of nfp
vnic=${2:-0} # The vNIC ID
numq=${3:-8} # number of queues to display
q_data_len=$(($numq * 16))

# There are 64 counters for each vnic, each counter is 64-bits counter
nfp-rtsym -n$dev -l464 -v -o ./.vnic_stats_data.txt _nic_stats_vnic:$((vnic*512))

nfp-rtsym -n$dev  -l$q_data_len -v -o ./.rxq_stats_data.txt nfd_cfg_base0:$((vnic*0x8000 + 0x1000))
nfp-rtsym -n$dev  -l$q_data_len -v -o ./.txq_stats_data.txt nfd_cfg_base0:$((vnic*0x8000 + 0x1400))

echo nfp$dev.vnic$vnic statistics:
parse_mem_for_64_bits_counters ./.vnic_stats_data.txt ./vnic_stats
parse_mem_for_64_bits_counters ./.rxq_stats_data.txt ./rxq_stats
parse_mem_for_64_bits_counters ./.txq_stats_data.txt ./txq_stats
